services:
  postgres:
    image: 'bitnami/postgresql:17.0.0'
    restart: 'always'
    environment:
      POSTGRESQL_USERNAME: '${POSTGRES_USERNAME:-postgres}'
      POSTGRESQL_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRESQL_DATABASE: '${POSTGRES_DATABASE:-app}'
    ports:
      - '11000:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
      - './scripts/wait-for-postgres.sh:/wait-for-postgres.sh'
    networks:
      - 'default'

  backend:
    image: 'node:22'
    restart: 'always'
    working_dir: '/app'
    command: 'yarn start:dev'
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DATABASE:-app}'
      LANGCHAIN_LLM_API_KEY: '${LANGCHAIN_LLM_API_KEY}'
      LANGCHAIN_LLM_MODEL: '${LANGCHAIN_LLM_MODEL}'
      LANGCHAIN_EMBEDDINGS_MODEL: '${LANGCHAIN_EMBEDDINGS_MODEL}'
      S3_ENDPOINT: '${S3_ENDPOINT}'
      S3_REGION: '${S3_REGION}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      S3_BUCKET: '${S3_BUCKET}'
      GEMINI_API_KEY: '${GEMINI_API_KEY}'
      GEMINI_MODEL: '${GEMINI_MODEL}'
      GEMINI_EMBEDDINGS_MODEL: '${GEMINI_EMBEDDINGS_MODEL}'
    ports:
      - '10000:3000'
    volumes:
      - './:/app'
    depends_on:
      - postgres

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
    driver: local
